version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/rtk-rnjn/algorithms"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"
