version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"