name: reviewdog

on:
  push:
    paths:
      - '**/*.java'

  pull_request:
    paths:
      - '**/*.java'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    name: runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Lint with CheckStyle
        run: |
          for file in $(find . -name '*.java'); do
            echo "Checking $file"
            exitcode=0
            java -jar ./utils/checkstyle.jar -c ./utils/checkstyle.xml $file > /dev/null 2>&1 || exitcode=$?
            if [ $exitcode -ne 0 ]; then
              output=$(java -jar ./utils/checkstyle.jar -c ./utils/checkstyle.xml $file)
              echo "$output"
            fi
          done
