name: C/C++ Syntax Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials (if needed)
        run: sudo apt update && sudo apt install -y build-essential

      - name: Check C syntax
        run: find . -name '*.c' -exec gcc -fsyntax-only {} \;

      - name: Check C++ syntax
        run: find . -name '*.cpp' -exec g++ -fsyntax-only {} \;