name: Java Syntax Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Set up Maven 3.9.5
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: '3.9.5'

      - name: Check Java syntax
        run: mvn -B validate
