name: Java Syntax Checker

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'

  pull_request:
    branches: [ main ]
    paths:
      - '**/*.java'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check Java Syntax
        run: |
            for file in $(git diff --name-only HEAD^ HEAD | grep '\.java$'); do
                echo "Checking $file"
                exitcode=0
                javac -Xlint:all $file || exitcode=$?
                if [ $exitcode -ne 0 ]; then
                    echo "Syntax check failed for $file"
                    exit 1
                fi
            done

