name: Java Syntax Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Check Java Syntax
        run: find . -name '*.java' -exec javac -Xlint:all -Xdiags:verbose -d temp/ {} \;
