name: Java Syntax Checker & Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'

  pull_request:
    branches: [ main ]
    paths:
      - '**/*.java'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 19
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Check Java Syntax
        run: find . -name '*.java' -exec javac -Xlint:all -Xdiags:verbose -d temp/ {} \;
